// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StokSayimApi.Data;

#nullable disable

namespace StokSayimApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260421000000_RedesignSchema")]
    partial class RedesignSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("StokSayimApi.Models.Branch", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("integer");
                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));
                b.Property<int>("CompanyId").HasColumnType("integer");
                b.Property<string>("Name").IsRequired().HasColumnType("text");
                b.HasKey("Id");
                b.HasIndex("CompanyId");
                b.ToTable("Branches");
            });

            modelBuilder.Entity("StokSayimApi.Models.Category", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("integer");
                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));
                b.Property<int>("CompanyId").HasColumnType("integer");
                b.Property<string>("Name").IsRequired().HasColumnType("text");
                b.HasKey("Id");
                b.ToTable("Categories");
            });

            modelBuilder.Entity("StokSayimApi.Models.Company", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("integer");
                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));
                b.Property<string>("Name").IsRequired().HasColumnType("text");
                b.HasKey("Id");
                b.ToTable("Companies");
            });

            modelBuilder.Entity("StokSayimApi.Models.Product", b =>
            {
                b.Property<int>("ProductId").HasColumnType("integer").ValueGeneratedNever();
                b.Property<string>("AltKategori").HasColumnType("text");
                b.Property<int>("CompanyId").HasColumnType("integer");
                b.Property<string>("Content").HasColumnType("text");
                b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
                b.Property<int>("KdvOrani").HasColumnType("integer");
                b.Property<string>("Kategori").HasColumnType("text");
                b.Property<string>("Marka").HasColumnType("text");
                b.Property<string>("ProductName").IsRequired().HasColumnType("text");
                b.Property<string>("Unit").IsRequired().HasColumnType("text");
                b.Property<DateTime>("UpdatedAt").HasColumnType("timestamp with time zone");
                b.HasKey("ProductId");
                b.HasIndex("CompanyId");
                b.ToTable("Products");
            });

            modelBuilder.Entity("StokSayimApi.Models.ProductBarcode", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("integer");
                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));
                b.Property<string>("Barcode").IsRequired().HasColumnType("text");
                b.Property<int>("CompanyId").HasColumnType("integer");
                b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
                b.Property<int>("ProductId").HasColumnType("integer");
                b.Property<string>("UnitType").IsRequired().HasColumnType("text");
                b.Property<double?>("UnitQuantity").HasColumnType("double precision");
                b.HasKey("Id");
                b.HasIndex("ProductId");
                b.HasIndex("CompanyId", "Barcode", "UnitType").IsUnique();
                b.ToTable("ProductBarcodes");
            });

            modelBuilder.Entity("StokSayimApi.Models.ProductPrice", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("integer");
                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));
                b.Property<double>("AlisFiyati").HasColumnType("double precision");
                b.Property<DateTime>("GecerlilikTarihi").HasColumnType("timestamp with time zone");
                b.Property<int?>("OlusturanUserId").HasColumnType("integer");
                b.Property<int>("ProductId").HasColumnType("integer");
                b.Property<double>("SatisFiyati").HasColumnType("double precision");
                b.Property<string>("UnitType").IsRequired().HasColumnType("text");
                b.HasKey("Id");
                b.HasIndex("ProductId", "UnitType");
                b.ToTable("ProductPrices");
            });

            modelBuilder.Entity("StokSayimApi.Models.SecMarketSyncLog", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("integer");
                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));
                b.Property<int>("BarcodesAdded").HasColumnType("integer");
                b.Property<int>("BarcodesSkipped").HasColumnType("integer");
                b.Property<string>("Notes").HasColumnType("text");
                b.Property<int>("ProductsAdded").HasColumnType("integer");
                b.Property<string>("SourceFile").IsRequired().HasColumnType("text");
                b.Property<string>("Status").IsRequired().HasColumnType("text");
                b.Property<DateTime>("SyncedAt").HasColumnType("timestamp with time zone");
                b.HasKey("Id");
                b.ToTable("SecMarketSyncLogs");
            });

            modelBuilder.Entity("StokSayimApi.Models.StockCount", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("integer");
                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));
                b.Property<int>("BranchId").HasColumnType("integer");
                b.Property<DateTime?>("CompletedAt").HasColumnType("timestamp with time zone");
                b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
                b.Property<int>("CreatedByUserId").HasColumnType("integer");
                b.Property<string>("Name").IsRequired().HasColumnType("text");
                b.Property<string>("Status").IsRequired().HasColumnType("text");
                b.HasKey("Id");
                b.ToTable("StockCounts");
            });

            modelBuilder.Entity("StokSayimApi.Models.StockCountItem", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("integer");
                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));
                b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
                b.Property<int>("ProductId").HasColumnType("integer");
                b.Property<double>("Stock").HasColumnType("double precision");
                b.Property<int>("StockCountId").HasColumnType("integer");
                b.Property<DateTime>("UpdatedAt").HasColumnType("timestamp with time zone");
                b.HasKey("Id");
                b.HasIndex("StockCountId", "ProductId").IsUnique();
                b.ToTable("StockCountItems");
            });

            modelBuilder.Entity("StokSayimApi.Models.SubCategory", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("integer");
                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));
                b.Property<int>("CategoryId").HasColumnType("integer");
                b.Property<string>("Name").IsRequired().HasColumnType("text");
                b.HasKey("Id");
                b.HasIndex("CategoryId");
                b.ToTable("SubCategories");
            });

            modelBuilder.Entity("StokSayimApi.Models.User", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("integer");
                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));
                b.Property<int>("CompanyId").HasColumnType("integer");
                b.Property<string>("PasswordHash").IsRequired().HasColumnType("text");
                b.Property<string>("Role").IsRequired().HasColumnType("text");
                b.Property<string>("Username").IsRequired().HasColumnType("text");
                b.HasKey("Id");
                b.HasIndex("Username", "CompanyId").IsUnique();
                b.ToTable("Users");
            });

            modelBuilder.Entity("StokSayimApi.Models.UserBranch", b =>
            {
                b.Property<int>("UserId").HasColumnType("integer");
                b.Property<int>("BranchId").HasColumnType("integer");
                b.HasKey("UserId", "BranchId");
                b.ToTable("UserBranches");
            });

            // ─── Relationships ─────────────────────────────────────────────────

            modelBuilder.Entity("StokSayimApi.Models.Branch", b =>
                b.HasOne("StokSayimApi.Models.Company", "Company")
                    .WithMany("Branches").HasForeignKey("CompanyId").OnDelete(DeleteBehavior.Cascade).IsRequired());

            modelBuilder.Entity("StokSayimApi.Models.Category", b =>
                b.HasOne("StokSayimApi.Models.Company", "Company")
                    .WithMany().HasForeignKey("CompanyId").OnDelete(DeleteBehavior.Cascade).IsRequired());

            modelBuilder.Entity("StokSayimApi.Models.Product", b =>
                b.HasOne("StokSayimApi.Models.Company", "Company")
                    .WithMany().HasForeignKey("CompanyId").OnDelete(DeleteBehavior.Cascade).IsRequired());

            modelBuilder.Entity("StokSayimApi.Models.ProductBarcode", b =>
                b.HasOne("StokSayimApi.Models.Product", "Product")
                    .WithMany("Barcodes").HasForeignKey("ProductId").OnDelete(DeleteBehavior.Cascade).IsRequired());

            modelBuilder.Entity("StokSayimApi.Models.ProductPrice", b =>
                b.HasOne("StokSayimApi.Models.Product", "Product")
                    .WithMany("Prices").HasForeignKey("ProductId").OnDelete(DeleteBehavior.Cascade).IsRequired());

            modelBuilder.Entity("StokSayimApi.Models.StockCount", b =>
            {
                b.HasOne("StokSayimApi.Models.Branch", "Branch")
                    .WithMany().HasForeignKey("BranchId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                b.HasOne("StokSayimApi.Models.User", "CreatedByUser")
                    .WithMany().HasForeignKey("CreatedByUserId").OnDelete(DeleteBehavior.Cascade).IsRequired();
            });

            modelBuilder.Entity("StokSayimApi.Models.StockCountItem", b =>
            {
                b.HasOne("StokSayimApi.Models.Product", "Product")
                    .WithMany("StockCountItems").HasForeignKey("ProductId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                b.HasOne("StokSayimApi.Models.StockCount", "StockCount")
                    .WithMany("Items").HasForeignKey("StockCountId").OnDelete(DeleteBehavior.Cascade).IsRequired();
            });

            modelBuilder.Entity("StokSayimApi.Models.SubCategory", b =>
                b.HasOne("StokSayimApi.Models.Category", "Category")
                    .WithMany("SubCategories").HasForeignKey("CategoryId").OnDelete(DeleteBehavior.Cascade).IsRequired());

            modelBuilder.Entity("StokSayimApi.Models.User", b =>
                b.HasOne("StokSayimApi.Models.Company", "Company")
                    .WithMany().HasForeignKey("CompanyId").OnDelete(DeleteBehavior.Cascade).IsRequired());

            modelBuilder.Entity("StokSayimApi.Models.UserBranch", b =>
            {
                b.HasOne("StokSayimApi.Models.User", "User")
                    .WithMany("UserBranches").HasForeignKey("UserId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                b.HasOne("StokSayimApi.Models.Branch", "Branch")
                    .WithMany().HasForeignKey("BranchId").OnDelete(DeleteBehavior.Cascade).IsRequired();
            });
#pragma warning restore 612, 618
        }
    }
}
